CREATE DATABASE IF NOT EXISTS naeil_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'naeil_app'@'localhost'
IDENTIFIED BY 'naeil1234!';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON naeil_db.*
TO 'naeil_app'@'localhost';

FLUSH PRIVILEGES;
